%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\RANProject\TestSequences\20210907_145202\zedBox_gnd_match.txt
%
% Auto-generated by MATLAB on 29-Oct-2021 19:36:32

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "png0Subject241Subject192Others"];
opts.SelectedVariableNames = "png0Subject241Subject192Others";
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "png0Subject241Subject192Others"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "png0Subject241Subject192Others"], "EmptyFieldRule", "auto");

% Import the data




%% Clear temporary variables

src_path = 'D:\RANProject\src2\src';
cd(src_path)
load("Offsets.mat")
cd(sequences_path)


files = dir(sequences_path+"/*");
files(ismember( {files.name}, {'.', '..'})) = [];  %remove . and ..
% Get a logical vector that tells which is a directory.
dirFlags = [files.isdir];
% Extract only those that are directories.
subFolders = files(dirFlags);
% Print folder names to command window.

for k = 1 : size(subFolders,1)
    cd(sequences_path+"/"+subFolders(k).name)
    zedBoxgndmatch = readtable(sequences_path+"/"+subFolders(k).name+"/"+"zedBox_gnd_match.txt", opts);
    subFolders(k).name
    gndphoneholders = zedBoxgndmatch;
    gndphoneholders = table2cell(gndphoneholders);
    if k==1 || k==2
        phoneholders = ["Subject24","Subject19"];
    else
        phoneholders = ["Subject24","Subject19","Subject11"];
    end

    for n=1:numel(gndphoneholders)
        names = string(gndphoneholders(n));
        newnames = split(names,',')
        TF = contains(newnames,phoneholders);
        NoOfPohneHolsers(n) = sum(TF);
    end
    NoOfPohneHolsers = NoOfPohneHolsers';
    save(subFolders(k).name+"NoOfPohneHolsers",'NoOfPohneHolsers')
end
%%

