function Pixel = importIMUfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PIXEL = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  PIXEL = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Pixel = importfile("Pixel.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Aug-2020 18:42:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timestamp", "tag", "x", "y", "z", "VarName6"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "tag", "EmptyFieldRule", "auto");

% Import the data
Pixel = readtable(filename, opts);
