function NewZedbboxwithdepthbbx30fpsimg3fps = ZedGNDStringimportfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NEWZEDBBOXWITHDEPTHBBX30FPSIMG3FPS = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  NEWZEDBBOXWITHDEPTHBBX30FPSIMG3FPS = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NewZedbboxwithdepthbbx30fpsimg3fps = importfile("C:\RANProject\WINLABData\20211007_113104\NewZed_bbox_with_depth_bbx30fps_img3fps.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Oct-2021 21:11:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName2", "EmptyFieldRule", "auto");

% Import the data
NewZedbboxwithdepthbbx30fpsimg3fps = readtable(filename, opts);
end