function Zedbboxwithdepthbbx30fpsimg3fps = ZedGNDimportfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ZEDBBOXWITHDEPTHBBX30FPSIMG3FPS = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  ZEDBBOXWITHDEPTHBBX30FPSIMG3FPS = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Zedbboxwithdepthbbx30fpsimg3fps = importfile("C:\Users\aalali\CameraIMUCorrelation\Trials\NewTrials\20201223_140951\Zed_bbox_with_depth_bbx30fps_img3fps.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Mar-2021 02:47:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timestamp", "frameNo", "trackID", "bbx", "bby", "bbw", "bbh", "depth", "range"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "timestamp", "InputFormat", "yyy-MM-dd HH_mm_ss.SSSSSS");

% Import the data
Zedbboxwithdepthbbx30fpsimg3fps = readtable(filename, opts);

end